# Created by thopper91 (2017)

- name: Add IPv4 '{{ SubnetName }}' Subnet
  oneview_id_pools_ipv4_subnet:
    config: "{{ config }}"
    state: present
    data:
      name: "{{ SubnetName }}"
      type: "Subnet"
      networkId: "{{ SubnetID }}" #Subnet ID in OneView
      subnetmask: "{{ SubnetMask }}"
      gateway: "{{ IPv4_Gateway }}"
      domain: "{{ IPv4_Domain }}"
      dnsServers: []
  delegate_to: localhost

- name: Gather facts about '{{ SubnetName }}' IPV4 Subnets
  oneview_id_pools_ipv4_subnet_facts:
    config: "{{ config }}"
    name: "{{ SubnetName }}"
- set_fact: subnet_uri="{{ id_pools_ipv4_subnets[0].uri }}"

- name: Add IPv4 '{{ RangeName }}' Range
  oneview_id_pools_ipv4_range:
    config: "{{ config }}"
    state: present
    data:
      name: "{{ RangeName }}"
      subnetUri: "{{ subnet_uri }}"
      type: "Range"
      rangeCategory: "Custom"
      startAddress: "{{ IPv4StartAddress }}"
      endAddress: "{{ IPv4EndAddress }}"
  delegate_to: localhost

- name: Ensure the IPv4 '{{ RangeName }}' Range is enabled
  oneview_id_pools_ipv4_range:
    config: "{{ config }}"
    state: present
    data:
      name: "{{ RangeName }}"
      subnetUri: "{{ subnet_uri }}"
      enabled: True
  delegate_to: localhost
