# Created by thopper91 (2017)

- name: Power On the server hardware
  oneview_server_hardware:
    config: "{{ config }}"
    state: power_state_set
    data:
        name : "{{ Serv_bay }}" #Choose a bay and server to turn on
        powerStateData:
            powerState: "Off"
            powerControl: "MomentaryPress"
  delegate_to: localhost
