# Created by thopper91 (2017)

- name: Create a basic connection-less server profile template (using names)
  oneview_server_profile_template:
    config: "{{ config }}"
    state: present
    data:
      name: "{{ TemplateName }}"
      description: "{{ Description }}"
      serverHardwareTypeName: "{{ Serv_Type }}"
      enclosureGroupName: "{{ Enclosure_Group }}"
      bootMode:
        manageMode: True
        mode: "UEFI"
      connections:
        - id: 1
          name: "{{ DMZ_VLAN }}"
          functionType: "{{ NetworkTypeEthernet }}"
          portId: "Auto"
          requestedMbps: 2500 #2.5Gb
          networkName: "{{ DMZ_VLAN }}"
          boot:
            priority: "NotBootable"
        - id: 2
          name: "{{ NetworkSanA }}"
          functionType: "{{ NetworkTypeFibreChannel }}"
          portId: "Auto"
          requestedMbps: 8000 #8Gb
          networkName: "{{ NetworkSanA }}"
          boot:
            priority: "NotBootable"
        - id: 3
          name: "{{ DeploymentNetwork }}"
          functionType: "{{ NetworkTypeEthernet }}"
          portId: "Auto"
          requestedMbps: 2500 #2.5Gb
          networkName: "{{ DeploymentNetwork }}"
          boot:
            priority: "Primary"
      sanStorage:
        hostOSType: 'Windows 2012 / WS2012 R2'
        manageSanStorage: true
        volumeAttachments:
          - id: 1
            volumeName: '{{ VolumeName }}'
            volumeStoragePoolName:  "{{ VolumeStoragePoolName }}"
            volumeStorageSystemName: "{{ VolumeStorageSystem }}"
            lunType: "Manual"
            lun: 0
            storagePaths:
              - isEnabled: true
                connectionId: 2
                storageTargetType: 'Auto'

- debug: var=server_profile
