- name: Gather facts about a Server Hardware by name
  oneview_server_hardware_facts:
    config:  "{{ config }}"
    name: "{{ Serv_b1 }}"
  delegate_to: localhost
- set_fact: Serv_Bay_ip="{{ server_hardwares[0].mpHostInfo.mpIpAddresses[1].address }}"

- name: Deploy OS
  hpe_icsp_os_deployment:
    icsp_host: "{{ ICSP_Host }}"
    username: "{{ ICSP_Username }}"
    password: "{{ ICSP_Password }}"
    server_ipAddress: "{{ Serv_Bay_ip }}"
    os_build_plan: "Jeffs_attempt_ProLiant OS - ESXi 6.5 Scripted Install"
  delegate_to: localhost
