# Playbook to run an additional playbook within the roles folder
#   - This is to attach an ILO to a server profile within OneView
#
#
# Created by thopper91 (2017)
---
- hosts: all
  connection: local
  roles:
    - {role: Attach_disk_to_ILO}
