# Playbook to run an additional playbook within the roles folder
#   - This is to create a provate volume in OneView
#
#
# Created by thopper91 (2017)
---
- hosts: all
  connection: local
  roles:
    - {role: Create_Private_Storage_Volume}
