# Playbook to run an additional playbook within the roles folder
#   - This is to create a basic server profile within OneView
#
#
# Created by thopper91 (2017)
---
- hosts: all
  connection: local
  roles:
    - {role: Create_Basic_Disk_Template}
