# This Playbook is to run an additional playbook within the roles folder:
#   - Create a User for OneView
#
#
# Created by thopper91 (2017)
---
- hosts: all
  connection: local
  roles:
    - {role: Create_User}
