# This Playbook is to run two additional playbook within the roles folder:
#   - Create a server profile with local storage
#   - Attach an ILO disk to the profile
#
#
# Created by thopper91 (2017)
---
- hosts: all
  connection: local
  roles:
    - {role: Create_Server_Profile_with_Local_Storage}
    - {role: Attach_disk_to_ILO}
