# This Playbook is to run an additional playbook within the roles folder:
#   - Delete a Fibre channel Network
#
#
# Created by thopper91 (2017)
---
- hosts: all
  connection: local
  gather_facts: True
  roles:
    - {role: Delete_Fibre_Channel_Network}
