# This Playbook is to run a set additional playbook within the roles folder.
# These playbooks are to do a full enclosure provision to prevent any manual work:
#   - Create a yse
#   - Ensure the time and locale configuration is correct
#   - Create IPv4 Subnet
#   - Create IPv4 Range and to ensure it is Enabled
#   - Create SAN Manager
#   - Create Storage system with its pools
#   - Add the networks
#   - Put them into network sets
#   - Gather all the networks URIs
#   - Create LIGs
#   - Create Enclosure Groups
#   - Create Logical Enclosures
#
# NOTE #1: Further work will need to go into this to ensure the variables are entered in
# correctly and the correct amount to items (networks, users etc) are added in manually.
# Once all of these values are placed, it should take a maximum of 30mins to provision the enclosure
# rather than days
#
# NOTE #2: If prefered, there is a full provision playbook in roles
#
# Created by thopper91 (2017)
---
- hosts: all
  connection: local
  roles:
    - {role: Create_User}
    - {role: Appliance_Time_and_Locale_Configuration}
    - {role: Create_IPv4_Subnet}
    - {role: Create_IPv4_Ranges}
    - {role: Ensure_IPv4_Range_is_Enabled}
    - {role: Create_SAN_Manager}
    - {role: Create_Storage_System_with_Pools}
    - {role: Create_Current_Network_Setup}
    - {role: Create_Network_Sets}
    - {role: Gather_all_Network_Uris}
    - {role: Create_Logical_Interconnect_Group}
    - {role: Create_Enclosure_Group}
    - {role: Create_Logical_Enclosure}
