# Created by thopper91 (2017)

- name: Create a Network Set
  oneview_network_set:
    config: "{{ config }}"
    state: present
    data:
      name: "{{ NetworkSetOne }}"
      networkUris: #From this point on, choose the networks needed (Ethernet)
        - "{{ Cust_VLAN }}"

- name: Create a Network Set
  oneview_network_set:
    config: "{{ config }}"
    state: present
    data:
      name: "{{ NetworkSetTwo }}"
      networkUris: #From this point on, choose the networks needed (Ethernet)
        - "{{ DMZ_VLAN }}"
        - "{{ Man_VLAN }}"
