# Created by thopper91 (2017)

- name: Gather facts about deployment network & Store variable
  oneview_ethernet_network_facts:
    config: "{{ config }}"
    name: "{{ DeploymentNetwork }}"
- set_fact: NET_Deploy_Uri="{{ ethernet_networks[0].uri }}"

- name: Gather facts about customer VLAN network & Store variable
  oneview_ethernet_network_facts:
    config: "{{ config }}"
    name: "{{ Cust_VLAN }}"
- set_fact: NET_VLANCust_Uri="{{ ethernet_networks[0].uri }}"

- name: Gather facts about Management VLAN network & Store variable
  oneview_ethernet_network_facts:
    config: "{{ config }}"
    name: "{{ Man_VLAN }}"
- set_fact: NET_VLANMan_Uri="{{ ethernet_networks[0].uri }}"

- name: Gather facts about DMZ VLAN network & Store variable
  oneview_ethernet_network_facts:
    config: "{{ config }}"
    name: "{{ DMZ_VLAN }}"
- set_fact: NET_VLANDMZ_Uri="{{ ethernet_networks[0].uri }}"

- name: Gather facts about San A network & Store variable
  oneview_fc_network_facts:
    config: "{{ config }}"
    name: "{{ NetworkSanA }}"
- set_fact: NET_SAN_A_Uri="{{ fc_networks[0].uri }}"

- name: Gather facts about San A network & Store variable
  oneview_fc_network_facts:
    config: "{{ config }}"
    name: "{{ NetworkSanB }}"
- set_fact: NET_SAN_B_Uri="{{ fc_networks[0].uri }}"

- name: Ensure that the Logical Interconnect Group is present
  oneview_logical_interconnect_group:
    config: "{{ config }}"
    state: present
    data:
      name: "{{ LIGName }}"
      enclosureIndexes: [1]
      enclosureType: "{{ EnclosureType }}"
      interconnectBaySet: 3
      redundancyType: "Redundant"
### Now for the interconnect connections
      interconnectMapTemplate:
        interconnectMapEntryTemplates:
          - logicalDownlinkUri: ~
            logicalLocation:
                locationEntries:
                    - relativeValue: 3
                      type: "Bay"
                    - relativeValue: 1
                      type: "Enclosure"
            permittedInterconnectTypeName: "{{ InterconType40 }}"
          - logicalDownlinkUri: ~
            logicalLocation:
                locationEntries:
                    - relativeValue: 6
                      type: "Bay"
                    - relativeValue: 1
                      type: "Enclosure"
            permittedInterconnectTypeName: "{{ InterconType40 }}"
### This is the Uplink Set code. Everytime logical Port Config Infos appears, its a new uplink. For visual aid, a single '#' will be used to break up the code
      uplinkSets:
        - logicalPortConfigInfos:
          - desiredSpeed: "Auto"
            logicalLocation:
                  locationEntries:
                    - relativeValue: 6
                      type: "Bay"
                    - relativeValue: "{{ Port1 }}"
                      type: "Port"
                    - relativeValue: 1
                      type: "Enclosure"
          - desiredSpeed: "Auto"
            logicalLocation:
                  locationEntries:
                    - relativeValue: 6
                      type: "Bay"
                    - relativeValue: "{{ Port2 }}"
                      type: "Port"
                    - relativeValue: 1
                      type: "Enclosure"
          name: "{{ UplinkSanB }}"
          mode: "Auto"
          networkType: "FibreChannel" #Ethernet is the other option
          networkUris:
            - "{{ NET_SAN_B_Uri }}"
        - logicalPortConfigInfos:
          - desiredSpeed: "Auto"
            logicalLocation:
                  locationEntries:
                    - relativeValue: 3
                      type: "Bay"
                    - relativeValue: "{{ Port2 }}"
                      type: "Port"
                    - relativeValue: 1
                      type: "Enclosure"
          - desiredSpeed: "Auto"
            logicalLocation:
                  locationEntries:
                    - relativeValue: 3
                      type: "Bay"
                    - relativeValue: "{{ Port1 }}"
                      type: "Port"
                    - relativeValue: 1
                      type: "Enclosure"
          name: "{{ UplinkSanA }}"
          mode: "Auto"
          networkType: "FibreChannel" #Ethernet / FibreChannel are the options
          networkUris:
            - "{{ NET_SAN_A_Uri }}"
        - logicalPortConfigInfos:
          - desiredSpeed: "Auto"
            logicalLocation:
                  locationEntries:
                    - relativeValue: 3
                      type: "Bay"
                    - relativeValue: "{{ Port_Eth_FCoE_Q1_1 }}" #Ethernet + FCoE Capability
                      type: "Port"
                    - relativeValue: 1
                      type: "Enclosure"
          name: "{{ UplinkDeploy }}"
          mode: "Auto"
          networkType: "Ethernet" #Ethernet / FibreChannel are the options
          networkUris:
            - "{{ NET_Deploy_Uri }}"
        - logicalPortConfigInfos:
          - desiredSpeed: "Auto"
            logicalLocation:
                  locationEntries:
                    - relativeValue: 6
                      type: "Bay"
                    - relativeValue: "{{ Port_Eth_FCoE_Q3_1 }}" #Ethernet + FCoE Capability
                      type: "Port"
                    - relativeValue: 1
                      type: "Enclosure"
          - desiredSpeed: "Auto"
            logicalLocation:
                  locationEntries:
                    - relativeValue: 6
                      type: "Bay"
                    - relativeValue: "{{ Port_Eth_FCoE_Q4_1 }}" #Ethernet + FCoE Capability
                      type: "Port"
                    - relativeValue: 1
                      type: "Enclosure"
          - desiredSpeed: "Auto"
            logicalLocation:
                  locationEntries:
                    - relativeValue: 3
                      type: "Bay"
                    - relativeValue: "{{ Port_Eth_FCoE_Q3_1 }}" #Ethernet + FCoE Capability
                      type: "Port"
                    - relativeValue: 1
                      type: "Enclosure"
          - desiredSpeed: "Auto"
            logicalLocation:
                  locationEntries:
                    - relativeValue: 3
                      type: "Bay"
                    - relativeValue: "{{ Port_Eth_FCoE_Q4_1 }}" #Ethernet + FCoE Capability
                      type: "Port"
                    - relativeValue: 1
                      type: "Enclosure"
          name: "{{ UplinkLAN }}"
          mode: "Auto"
          networkType: "Ethernet" #Ethernet / FibreChannel are the options
          networkUris:
            - "{{ NET_VLANDMZ_Uri }}"
            - "{{ NET_VLANMan_Uri }}"
            - "{{ NET_VLANCust_Uri }}"
