---
config: '{{ playbook_dir }}/config.json'
IPv4_Domain: 'awesome.com'
IPv4_Gateway: '10.10.1.1'
IPv4EndAddress: '10.10.4.50'
IPv4StartAddress: '10.10.4.2'
RangeName: 'Range 1'
SubnetID: 'Subnet ID in OneView'
SubnetName: '10.10.10.10'
SubnetMask: '255.255.255.0'
