# Playbook to run an additional playbook within the roles folder
#   - This is to create a server profile template within OneView
#
#
# Created by thopper91 (2017)
---
- hosts: all
  connection: local
  roles:
    - {role: Create_Server_Profile_Template}
