# Include all variable files in the vars folder
#
- name: Include all variable files
  include_vars:
    dir: 'vars' #change directory if needed
    extensions:
        - yml
#
# Gather information
#
- name: Gather facts about a Server Hardware by name
  oneview_server_hardware_facts:
#    config:  "{{ config }}"
    name: "{{ Serv_b1 }}"
  delegate_to: localhost
- set_fact: Serv_Bay_ip="{{ server_hardwares[0].mpHostInfo.mpIpAddresses[1].address }}"

- debug:
   msg: "Just gathered relevant information :) Lets create the Profile in OneView first"
#
# Begin the creation of profile
#
- name: Create Profile with Local Storage
  oneview_server_profile:
#    config: "{{ config }}"
    state: present
    data:
      name: "{{ Prof_Name }}"
      description: "{{ Prof_Description }}"
      server_hardware: "{{ Serv_b1 }}"
      serverHardwareTypeName: "{{ Serv_Type660 }}"
      enclosureGroupName: "{{ Enclosure_Group }}"
#
# Boot mode and Setting are requred
#
      bootMode:
        manageMode: True
        mode: "BIOS"
        pxeBootPolicy: "Auto"
      boot:
        manageBoot: True
        order:
        - "CD"
        - "USB"
        - "HardDisk"
        - "PXE"
#
# BIOS.
# If BIOS is needed, managebios needs to be True otherwise default is false.
# The over-written settings are the items changed from the default
#
      bios:
        manageBios: "true"
        overriddenSettings:
          - id: "PowerRegulator"
            value: "StaticHighPerf"
          - id: "MinProcIdlePkgState"
            value: "NoState"
          - id: "MinProcIdlePower"
            value: "NoCStates"
          - id: "PowerProfile"
            value: "MaxPerf"
          - id: "IntelQpiPowerManagement"
            value: "Disabled"
          - id: "EnergyPerfBias"
            value: "MaxPerf"
          - id: "VirtualInstallDisk"
            value: "Enabled"
#
# Local Storage
#
      localStorage:
        controllers:
          - deviceSlot: "Embedded"
            mode: "RAID"
            initialize: False #Initialize storage on next profile
            importConfiguration: false #Import existing logical Drives
            logicalDrives:
              - name: "{{ Local_Stor_Name }}"
                raidLevel: "RAID1"
                numPhysicalDrives: 2
                driveTechnology: "null"
                bootable: true
#
# Network connections.
# FC networks are required for the SAN storages
#
      connections:
        - id: 1
          name: "{{ Man_VLAN }}"
          functionType: "Ethernet"
          portId: "Mezz 3:2-a"
          requestedMbps: 2500 #2.5Gb
          networkName: "{{ Man_VLAN }}"
          boot:
            priority: "NotBootable"
        - id: 2
          name: "{{ Cust_VLAN }}"
          functionType: "Ethernet"
          portId: "Auto"
          requestedMbps: 2500 #2.5Gb
          networkName: "{{ Cust_VLAN }}"
          boot:
            priority: "NotBootable"
#
# Power on Server Profile
#
- name: Power On the server hardware
  oneview_server_hardware:
#    config: "{{ config }}"
    state: power_state_set
    data:
        name : "{{ Serv_b3 }}" #The Server HW name
        powerStateData:
            powerState: "On"
            powerControl: "MomentaryPress" #MomentaryPress and PressAndHold are the two options
  delegate_to: localhost
#
#
#
- debug:
   msg: "Profile created, now creating a server in ICsp"

- name: Ensure the server is registered in ICsp
  hpe_icsp_server:
    icsp_host: "{{ ICSP_Host }}"
    username: "{{ ICSP_Username }}"
    password: "{{ ICSP_Password }}"
    server_ipAddress: "{{ Serv_Bay_ip }}"
    server_username: "{{ ilo_Username }}"
    server_password: "{{ ilo_Password }}"
    state: present
  delegate_to: localhost

- debug:
   msg: "Server registered in ICsp, Lets deploy the OS"

- name: Deploy OS
  hpe_icsp_os_deployment:
    icsp_host: "{{ ICSP_Host }}"
    username: "{{ ICSP_Username }}"
    password: "{{ ICSP_Password }}"
    server_ipAddress: "{{ Serv_Bay_ip }}"
    os_build_plan: "Jeffs_attempt_ProLiant OS - ESXi 6.5 Scripted Install"
  delegate_to: localhost

- debug:
   msg: "OS Deployed Successfully"
