# Created by thopper91 (2017)

- name: Add '{{ SubnetName }}' IPv4 Subnet
  oneview_id_pools_ipv4_subnet:
    config: "{{ config }}"
    state: present
    data:
      name: "{{ SubnetName }}"
      type: "Subnet"
      networkId: "{{ SubnetID }}" #Subnet ID in OneView
      subnetmask: "{{ IPv4SubnetMask }}"
      gateway: "{{ IPv4Gateway }}"
      domain: "{{ IPv4Domain }}"
      dnsServers: []
  delegate_to: localhost
