# Created by thopper91 (2017)
 
- name: Gather facts about Enclosure Group
  oneview_enclosure_group_facts:
#    config: "{{ config }}"
    name: "{{ Enclosure_Group }}"
  delegate_to: localhost
- set_fact: Encl_Group_Uri="{{ enclosure_groups[0].uri }}"

- name: Gather facts about Deployment network uri
  oneview_ethernet_network_facts:
#    config: "{{ config }}"
    name: "{{ Deploy_NET }}"
- set_fact: NET_Deploy_Uri="{{ ethernet_networks[0].uri }}"
#
#
- name: Ensure that Enclosure Group is present using the default configuration
  oneview_enclosure_group:
#    config: "{{ config }}"
    state: present
    data:
      name: "{{ Enclosure_Group }}"
      description: "{{ Encl_Description}}"
      powerMode: "RedundantPowerFeed"
      enclosureType: "SY12000"
      stackingMode: "Enclosure"
      enclsoureCount: 1
      interconnectBayMappingCount: 2
      interconnectBayMappings:
        - interconnectBay: 1
        - interconnectBay: 2
        - interconnectBay: 3
          logicalInterconnectGroupUri: "{{ Encl_Group_Uri }}" #  SYN-DBPOC-EG
        - interconnectBay: 4
        - interconnectBay: 5
        - interconnectBay: 6
          logicalInterconnectGroupUri: "{{ Encl_Group_Uri }}" #  SYN-DBPOC-EG
#
# IP Section: Uri is the Management IP added in settings...NOT in Networks
#
      ipAddressingMode: "IpPool"
      ipRangeUris:
        - "{{ IP_Range_Uri }}"
#
# OS Deploment Settings
#
      osDeploymentSettings:
        manageOSDeployment: true
        deploymentModeSettings:
          deploymentMode: "External"
          deploymentNetworkUri: "{{ NET_Deploy_Uri }}"
