# Created by thopper91 (2017)

- name: Create a basic connection-less server profile template (using names)
  oneview_server_profile_template:
    config: "{{ config }}"
    state: present
    data:
      name: "{{ ProfileTemplateName }}"
      description: "{{ ProfileDescription }}"
      serverHardwareTypeName: "{{ Serv_Type }}"
      enclosureGroupName: "{{ Enclosure_Group }}"
      bootMode:
        manageMode: True
        mode: "UEFI"
      connections:
        - id: 1
          name: "{{ DMZ_VLAN }}"
          functionType: "{{ NetworkTypeEthernet }}"
          portId: "Auto"
          requestedMbps: 2500 #2.5Gb
          networkName: "{{ DMZ_VLAN }}"
          boot:
            priority: "NotBootable"
        - id: 2
          name: "{{ NetworkSanA }}"
          functionType: "{{ NetworkTypeFibreChannel }}"
          portId: "Auto"
          requestedMbps: 8000 #8Gb
          networkName: "{{ NetworkSanA }}"
          boot:
            priority: "NotBootable"
        - id: 3
          name: "{{ Man_VLAN }}"
          functionType: "{{ NetworkTypeEthernet }}"
          portId: "Auto"
          requestedMbps: 2500 #2.5Gb
          networkName: "{{ Man_VLAN }}"
          boot:
            priority: "NotBootable"
        - id: 4
          name: "{{ Cust_VLAN }}"
          functionType: "{{ NET_Eth }}"
          portId: "Auto"
          requestedMbps: 2500 #2.5Gb
          networkName: "{{ Cust_VLAN }}"
          boot:
            priority: "NotBootable"
      sanStorage:
        hostOSType: 'Windows 2012 / WS2012 R2'
        manageSanStorage: true
        volumeAttachments:
          - id: 1
            volumeName: "{{ VolumeName }}"
            volumeStoragePoolName: "{{ VolumeStoragePool }}"
            volumeStorageSystemName: "{{ VolumeStorageSystem }}"
            lunType: "Manual"
            lun: 0
            storagePaths:
              - isEnabled: true
                connectionId: 2
                storageTargetType: 'Auto'
          - id: 2
            volumeName: "{{ Vol_Name_2 }}"
            volumeStoragePoolName: "{{ Vol_Stor_Pool1 }}"
            volumeStorageSystemName: "{{ Vol_Stor_Sys }}"
            lunType: "Manual"
            lun: 1
            storagePaths:
              - isEnabled: true
                connectionId: 2
                storageTargetType: 'Auto'

- debug: var=server_profile
- debug: var=serial_number
- debug: var=server_hardware
- debug: var=compliance_preview
- debug: var=created
