- name: Power Off the server hardware
  oneview_server_hardware:
#    config: "{{ config }}"
    state: power_state_set
    data:
        name : "{{ Serv_b1 }}" #Choose a bay and server to turn on
        powerStateData:
            powerState: "Off"
            powerControl: "MomentaryPress"
  delegate_to: localhost


- name: Update Profile with Storage volume
  oneview_server_profile:
#    config: "{{ config }}"
    state: present
    data:
      name: "{{ Prof_Name }}"
      sanStorage:
        hostOSType: 'VMware (ESXi)'
        manageSanStorage: true
        volumeAttachments:
          - id: 1
            volumeName: "{{ Vol_Name_1 }}"
            volumeStoragePoolName: "{{ Vol_Stor_Pool5 }}"
            volumeStorageSystemName: "{{ Vol_Stor_Sys }}"
            lunType: "Manual"
            lun: 0
            storagePaths:
              - isEnabled: true
                connectionId: 6 #SAN-A ID in connections
                storageTargetType: 'Auto'
              - isEnabled: true
                connectionId: 7 #SAN-B ID in connections
                storageTargetType: 'Auto'
          - id: 2
            volumeName:  "{{ Vol_Name_2 }}"
            volumeStoragePoolName: "{{ Vol_Stor_Pool5 }}"
            volumeStorageSystemName: "{{ Vol_Stor_Sys }}"
            lunType: "Manual"
            lun: 1
            storagePaths:
              - isEnabled: true
                connectionId: 6 #SAN-A ID in connections
                storageTargetType: 'Auto'
              - isEnabled: true
                connectionId: 7 #SAN-B ID in connections
                storageTargetType: 'Auto'
          - id: 3
            volumeName: "{{ Vol_Name_3 }}"
            volumeStoragePoolName: "{{ Vol_Stor_Pool5 }}"
            volumeStorageSystemName: "{{ Vol_Stor_Sys }}"
            lunType: "Manual"
            lun: 2
            storagePaths:
              - isEnabled: true
                connectionId: 6 #SAN-A ID in connections
                storageTargetType: 'Auto'
              - isEnabled: true
                connectionId: 7 #SAN-B ID in connections
                storageTargetType: 'Auto'
  delegate_to: localhost

- name: Power On the server hardware
  oneview_server_hardware:
#    config: "{{ config }}"
    state: power_state_set
    data:
        name : "{{ Serv_b1 }}" #Choose a bay and server to turn on
        powerStateData:
            powerState: "On"
            powerControl: "MomentaryPress"
  delegate_to: localhost
