# Created by thopper91 (2017)

- name: Update '{{ Subnet_Name }}' Subent with the new Domain: '{{ IPv4_NewDomain }}'
  oneview_id_pools_ipv4_subnet:
    config: "{{ config }}"
    state: present
    data:
      name: "{{ Subnet_Name }}"
      domain: "{{ IPv4_NewDomain }}"
  delegate_to: localhost
