---
config: '{{ playbook_dir }}/config.json'
Cust_VLAN: 'Customer VLAN'
DeploymentNetwork: 'Deployment Network Name'
DMZ_VLAN: 'DMZ VLAN'
EnclosureType: 'SY12000'
InterconType40: 'Virtual Connect SE 40Gb F8 Module for Synergy'
LIGName: 'SYN-Test-LIG'
Man_VLAN: 'Management VLAN'
NetworkSanA: 'SAN-A'
NetworkSanB: 'SAN-B'
Port1: '62'
Port2: '67'
Port_Eth_FCoE_Q1_1: '87'
Port_Eth_FCoE_Q3_1: '72'
Port_Eth_FCoE_Q4_1: '77'
UplinkDeploy: 'Deployment-Uplink'
UplinkLAN: 'LAN-UplinkSet'
UplinkSanA: 'SAN-A-UplinkSet'
UplinkSanB: 'SAN-B-UplinkSet'
