# Created by thopper91 (2017)

- name: Create a basic connection-less server profile template (using names)
  oneview_server_profile:
    config: "{{ config }}"
    state: "present"
    data:
        name: "{{ ProfileName }}"
        description: "{{ ProfileDescription }}"
      sanStorage:
        hostOSType: 'VMware (ESXi)'
        manageSanStorage: true
        volumeAttachments:
          - id: 1
            volumeName: "{{ VolumeName }}"
            volumeStoragePoolName: "{{ VolumeStoragePool }}"
            volumeStorageSystemName: "{{ VolumeStorageSystem }}"
            lunType: "Auto"
            lun: 0
            storagePaths:
              - isEnabled: true
                connectionId: 6 #SAN-A
                storageTargetType: 'Auto'
              - isEnabled: true
                connectionId: 7 #SAN-B
                storageTargetType: 'Auto'
