# Created by thopper91 (2017)

- name: Gather facts about all Storage Pools
  oneview_storage_pool_facts:
    config: "{{ config }}"
    name: "{{ VolumeStoragePool }}"
- set_fact: VolumeStoragePoolUri="{{ storage_pools[0].uri }}"

- name: Gather facts about all Storage Systems
  oneview_storage_system_facts:
    config: "{{ config }}"
- set_fact: VolumeStorageSystemUri="{{ storage_systems[0].uri }}"

- name: Create Private Volume
  oneview_volume:
    config: "{{ config }}"
    state: present
    data:
      name: '{{ VolumeName }}'
      description: '{{ VolumeDescription }}'
      raidLevel: "RAID5"
      provisioningParameters:
          provisionType: "{{ Type }}"
          shareable: False
          requestedCapacity: "{{ memory }}"
          storagePoolUri: "{{ VolumeStoragePoolUri }}"
      storageSystemUri: "{{ VolumeStorageSystemUri }}"
      snapshotPoolUri: "{{ VolumeStoragePoolUri }}"
  delegate_to: localhost
