# Created by thopper91 (2017)

### Gather Network URI
- name: Gather URI information on {{ ContainVLAN }}
  oneview_ethernet_network_facts:
    config: "{{ config }}"
    name: "{{ ContainVLAN }}"
- set_fact: Network_uri="{{ ethernet_networks[0].uri }}"

### Gather Server Hardware Uri
- name: Gather Uri on {{ Serv_bay }} bay
  oneview_server_hardware_facts:
    config:  "{{ config }}"
    name: "{{ Serv_bay }}"
  delegate_to: localhost
- set_fact: Server_HW="{{ server_hardwares[0].uri }}"

### Begin the creation of profile
- name: Create "{{ ProfileName }}" profile for Openshift
  oneview_server_profile:
    config: "{{ config }}"
    state: present
    data:
      name: "{{ ProfileName }}"
      description: "{{ ProfileDescription }}"
      serverHardwareUri: "{{ Server_HW }}"
      serverHardwareTypeName: "{{ ServerType }}"
      enclosureGroupName: "{{ EnclosureGroup }}"
### This function of code is for the image streamer. If not needed, remove
      osDeploymentSettings:
        osDeploymentPlanName: "{{ deploy_plan_name }}"
        osCustomAttributes:
          -  name: VolumeSize
             value: "20000"
# Boot mode and Setting are requred
      bootMode:
        manageMode: True
        mode: "UEFI"
        pxeBootPolicy: "Auto"
      boot:
        manageBoot: True
        order:
        - "HardDisk"
### SAN Storage. The LUN starts at 0
      sanStorage:
        hostOSType: 'RHE Linux (5.x, 6.x)'
        manageSanStorage: true
        volumeAttachments:
          - id: 1
            volumeName: "{{ VolumeName }}"
            volumeStoragePoolName: "{{ VolumeStoragePoolName }}"
            volumeStorageSystemName: "{{ VolumeStorageSystem }}"
            lunType: "Auto"
            lun: 0
            isBootVolume: "true"
            storagePaths:
              - isEnabled: true
                connectionId: 3 #SAN-A
                storageTargetType: 'Auto'
              - isEnabled: true
                connectionId: 4 #SAN-B
                storageTargetType: 'Auto'
### Network connections. FC networks are required for the SAN storages
      connections:
        - id: 1
          name: "{{ DeploymentNetwork }}"
          functionType: "Ethernet"
          portId: "Mezz 3:1-a"
          requestedMbps: 2500 #2.5Gb
          networkName: "{{ DeploymentNetwork }}"
          boot:
            priority: "Primary" #used as it is an iSCSi network
        - id: 2
          name: "{{ ContainVLAN }}"
          functionType: "Ethernet"
          portId: "Mezz 3:1-c"
          requestedMbps: 2500 #2.5Gb
          networkName: "{{ ContainVLAN }}"
          boot:
            priority: "NotBootable"
        - id: 3
          name: "{{ NetworkSanA }}"
          functionType: "FibreChannel"
          portId: "Mezz 3:1-b"
          requestedMbps: 2500 #2.5Gb
          networkName: "{{ NetworkSanA }}"
          boot:
            priority: "NotBootable"
        - id: 4
          name: "{{ NetworkSanB }}"
          functionType: "FibreChannel"
          portId: "Mezz 3:2-b"
          requestedMbps: 2500 #2.5Gb
          networkName: "{{ NetworkSanB }}"
          boot:
            priority: "NotBootable"

- name: Gather facts about a Server Hardware by name
  oneview_server_hardware_facts:
    config:  "{{ config }}"
    name: "{{ Serv_bay }}"
  delegate_to: localhost
- set_fact: iloAddress="{{ server_hardwares[0].mpHostInfo.mpIpAddresses[1].address }}"

- name: Attach CentOS Atomic 7 iso to Profile
  hpilo_boot:
    host: "{{ iloAddress }}"
    login: "{{ iloUsername }}"
    password: "{{ iloPassword }}"
    media: cdrom
    image: "{{ RHEL7.3 }}"
  delegate_to: localhost

# Power on Server Profile
- name: Power On the server hardware
  oneview_server_hardware:
    config: "{{ config }}"
    state: power_state_set
    data:
        name : "{{ Serv_bay }}" #The Server HW name
        powerStateData:
            powerState: "On"
            powerControl: "MomentaryPress" #MomentaryPress and PressAndHold are the two options
  delegate_to: localhost
