# Created by thopper91 (2017)

- name: Creates a Device Manager for the Brocade SAN provider with the given hostname and credentials
  oneview_san_manager:
    config: '{{ config }}'
    state: present
    data:
      providerDisplayName: 'Brocade Network Advisor'
      connectionInfo:
        - name: Host
          value: "{{ SanManagerHost }}"
        - name: Port
          value: "{{ SanManagerPort }}"
        - name: Username
          value: "{{ SanManagerUsername }}"
        - name: Password
          value: "{{ SanManagerPassword }}"
        - name: UseSsl
          value: true
