---
config: '{{ playbook_dir }}/config.json'
Cust_VLAN: 'Customer VLAN'
Cust_VLAN_B: 'Customer VLAN B'
Deploy_NET: 'Deployment'
Enclosure_Group: 'SYN-Test-EG'
Man_VLAN: 'Management VLAN'
Man_VLAN_B: 'Management VLAN B'
NET_SAN_A: 'SAN-A'
NET_SAN_B: 'SAN-B'
Prof_Description: 'Insert description here for a server profile'
Prof_Name: 'Server Profile'
Serv_bay: 'ServerName, #'
Serv_Type660: 'SY 660 Gen9 1'
Vol_Name_1: 'ESXi-Shared-Vol-Data01'
Vol_Name_2: 'ESXi-Shared-Vol-Log-01'
Vol_Stor_Pool: 'Storage pool'
Vol_Stor_Sys: 'storage system'

### Ips
IP_Address: '10.0.0.1'
IP_Dns1: '0.5.0.1'
IP_Dns2: '0.5.0.2'
IP_Gateway: '10.0.8.1'
IP_SubNet: '255.255.255.0'
