# Created by thopper91 (2017)

- name: Ensures the Appliance time and locale configuration locale is en_US.UTF-8
  oneview_appliance_time_and_locale_configuration:
#    config: "{{ config }}"
    state: present
    data:
      locale: en_US.UTF-8
      ntpServers: [16.110.135.123]
      timezone: UTC
      type: TimeAndLocale
  delegate_to: localhost
