## Gather IPv4 Subnet information
- name: Gather facts about '{{ Subnet_Name }}' IPV4 Subnets
  oneview_id_pools_ipv4_subnet_facts:
#    config: "{{ config }}"
    name: "{{ Subnet_Name }}"
- set_fact: subnet_uri="{{ id_pools_ipv4_subnets[0].uri }}"

- name: Create Ethernet network for VLAN DMZ
  oneview_ethernet_network:
#    config: '{{ config }}'
    state: present
    data:
      name: '{{ DMZ_VLAN }}'
      vlanId: '201'
      privateNetwork: false
      smartLink: false
      purpose: Management
      bandwidth:
          maximumBandwidth: 20000
          typicalBandwidth: 2500

- name: Create Ethernet network for VLAN Management
  oneview_ethernet_network:
#    config: '{{ config }}'
    state: present
    data:
      name: '{{ Man_VLAN }}'
      vlanId: '202'
      privateNetwork: false
      smartLink: false
      purpose: Management
      bandwidth:
          maximumBandwidth: 20000
          typicalBandwidth: 2500

- name: Create Ethernet network for VLAN Customer
  oneview_ethernet_network:
#    config: '{{ config }}'
    state: present
    data:
      name: '{{ Cust_VLAN }}'
      vlanId: '203'
      privateNetwork: false
      smartLink: false
      purpose: Management
      bandwidth:
          maximumBandwidth: 20000
          typicalBandwidth: 2500

- name: Create Ethernet network for Management (Synergy)
  oneview_ethernet_network:
#    config: '{{ config }}'
    state: present
    data:
      name: '{{ Man_NET }}'
      vlanId: '1001'
      privateNetwork: false
      smartLink: false
      purpose: Management
      bandwidth:
          maximumBandwidth: 20000
          typicalBandwidth: 2500
      subnetUri: "{{ subnet_uri }}"

- name: Create Ethernet network for Deployment (Synergy)
  oneview_ethernet_network:
#    config: '{{ config }}'
    state: present
    data:
      name: '{{ Deploy_NET }}'
      vlanId: '1002'
      privateNetwork: false
      smartLink: false
      purpose: Management
      bandwidth:
          maximumBandwidth: 20000
          typicalBandwidth: 2500

- name: Gather facts about a Managed SAN by name
  oneview_managed_san_facts:
#    config: "{{ config }}"
    name: "{{ SAN_A }}"
  delegate_to: localhost
- set_fact: San_A_uri="{{ managed_sans[0].uri }}"

- name: Gather facts about a Managed SAN by name
  oneview_managed_san_facts:
#    config: "{{ config }}"
    name: "{{ SAN_B }}"
  delegate_to: localhost
- set_fact: San_B_uri="{{ managed_sans[0].uri }}"

- name: Create Fibre Channel network
  oneview_fc_network:
#    config: '{{ config }}'
    state: present
    data:
      name: '{{ NET_SAN_A }}'
      fabricType: 'FabricAttach'
      linkStabilityTime: '30'
      autoLoginRedistribution: true
      managedSanUri: '{{ SAN_A_Uri }}'

- name: Create Fibre Channel network
  oneview_fc_network:
#    config: '{{ config }}'
    state: present
    data:
      name: '{{ NET_SAN_B }}'
      fabricType: 'FabricAttach'
      linkStabilityTime: '30'
      autoLoginRedistribution: true
      managedSanUri: '{{ SAN_B_Uri }}'
